# Generated by Django 5.0 on 2023-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('TG_id', models.CharField(max_length=255, unique=True, verbose_name='Id пользователя в телеграм')),
                ('username', models.CharField(max_length=64, verbose_name='Ник пользователя')),
                ('subscribe', models.BooleanField(default=False, verbose_name='Есть ли подписка у пользователя?')),
                ('end_subscribe', models.DateTimeField(default=None, null=True, verbose_name='Дата окончания подписки')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
