# Generated by Django 5.0 on 2023-12-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_username_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=128, verbose_name='ID пользователя в телеграмме')),
                ('username', models.CharField(max_length=64, verbose_name='Ник пользовател в телеграмме')),
                ('subscription', models.BooleanField(default=False, verbose_name='Есть ли у пользователя подписка')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Является ли пользователь админом')),
                ('end_subscription', models.DateField(default=None, null=True, verbose_name='Дата окончания подписки')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
