# Generated by Django 5.0 on 2023-12-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_users_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название канала. Может быть любым')),
                ('channel_url', models.CharField(max_length=256, verbose_name='Ссылка на канал')),
                ('target_word', models.CharField(max_length=1024, verbose_name='Слова таргеты. Заполнять через запятую')),
                ('stop_word', models.CharField(max_length=1024, verbose_name='Стоп слова. Заполнять через запятую')),
                ('in_use', models.BooleanField(default=False, verbose_name='использовался ли этот канал ранее')),
                ('last_message', models.IntegerField(default=0, verbose_name='Последнее прочитанное соощение')),
            ],
        ),
    ]
