# Generated by Django 5.0 on 2023-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='need_send_contacts',
            field=models.BooleanField(default=False, verbose_name='Нужно ли отправлять сообщении контакты для связи'),
        ),
    ]
