# Generated by Django 5.0 on 2023-12-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_channels_need_send_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
            ],
        ),
        migrations.AlterField(
            model_name='channels',
            name='stop_word',
            field=models.CharField(max_length=1024, verbose_name='Стоп слова.'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='target_word',
            field=models.CharField(max_length=1024, verbose_name='Слова таргеты.'),
        ),
    ]
